apiVersion: v1
kind: Service
metadata:
  name: oracle-service
  namespace: zhongchuang
spec:
  type: NodePort
  ports:
  - name: oracle-port-1
    port: 22
    targetPort: 22
    nodePort: 31022
  - name: oracle-port-2
    port: 1521
    targetPort: 1521
    nodePort: 31521
  selector:
    app: oracle
